spring:
  application:
    name: jwt
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    url: jdbc:mysql://localhost:3306/jwt_test?serverTimezone=Asia/Seoul
    url: jdbc:log4jdbc:mysql://localhost:3306/jwt_test?serverTimezone=Asia/Seoul
    username: root
    password: tkdlek12


mybatis:
  mapper-locations: classpath:/mybatis/mapper/**/*.xml
  config-location: /mybatis/MybatisConfig.xml
  type-aliases-package: com.cos.jwt
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    jdbc:
      sqlonly: DEBUG
      sqltiming: DEBUg
      audit: OFF
      resulttest: OFF
      resulttesttable: DEBUG
      connection: OFF

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
      enabled: true
      force: true